"""Cross-language interop tests using fixtures generated by the JS SDK."""
from __future__ import annotations

import json
import os
from openpassport import verify_passport, verify_message

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "spec", "fixtures")


def _load(name: str) -> dict:
    with open(os.path.join(FIXTURES_DIR, name)) as f:
        return json.load(f)


def test_verify_js_generated_passport():
    """A passport created by the JS SDK should be verifiable by the Python SDK."""
    passport = _load("valid-passport.json")
    result = verify_passport(passport)
    assert result.valid, f"Expected valid, got errors: {result.errors}"


def test_verify_js_generated_envelope():
    """A message envelope created by the JS SDK should be verifiable by the Python SDK."""
    passport = _load("valid-passport.json")
    envelope = _load("valid-envelope.json")
    # Use a very large max_age since fixtures are not freshly generated
    result = verify_message(envelope, passport, max_age_seconds=999999999)
    assert result.valid, f"Expected valid, got errors: {result.errors}"
